name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Dashboard Repo
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Checkout GitOps Repo
      uses: actions/checkout@v4
      with:
        repository: reecetec/homelab-gitops 
        token: ${{ secrets.GITOPS_PAT }}      
        path: homelab-gitops                  

    - name: Update image tag in deployment.yaml
      run: |
        # Use sed to find the line starting with 'image:' and replace it.
        # The '|' is used as a separator to avoid issues with slashes in the image path.
        sed -i "s|image:.*|image: ${{ steps.meta.outputs.tags }}|" homelab-gitops/poc-dashboard/deployment.yaml
        
    - name: Commit and push changes
      run: |
        cd homelab-gitops
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add poc-dashboard/deployment.yaml
        # Commit only if there are changes
        if ! git diff --staged --quiet; then
          git commit -m "ci: Update poc-dashboard image to ${{ github.sha }}"
          git push
        else
          echo "No changes to commit."
        fi